[env]
TERM = "xterm-256color"

[window]
padding.x = 15 
padding.y = 15

[general]
import = [
  "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13.0
